### ISSUE TITLE
agregar cloud.mail.ru

### ISSUE THREAD

**Issue by rs3mk** [forestrf/Descargavideos#2]
agregar ese servidor ruso, muchos lo usan para colgar sus vídeos. Un ejemplo https://cloud.mail.ru/public/6f2p/K231H5ofP

gracias

**Comment by forestrf** [comment]
No hace falta que lo haga ya que esa web permite descargar el vídeo directamente.
Para hacerlo tienes que clicar el nombre del archivo, que está sobre el reproductor del vídeo.
